# 商家服务Docker环境配置
server:
  port: 8081
  servlet:
    context-path: /merchant

spring:
  application:
    name: merchant-service
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:shopping_ecommerce}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:shopping}
    password: ${MYSQL_PASSWORD:shopping123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Flyway配置 - Docker环境启用数据库迁移
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: ${MYSQL_DATABASE:shopping_ecommerce}
    
  # 邮件服务配置
  mail:
    host: smtp.163.com
    port: 465
    username: 18579776220@163.com
    password: RWpSmbKNgiNa24ib
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
            trust: smtp.163.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false
            
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hunric.model
  configuration:
    map-underscore-to-camel-case: true
    
# JWT配置
jwt:
  secret: hunric-shopping-ecommerce-merchant-jwt-secret-key-2024-very-long-secret
  expiration: 86400000  # 24小时（毫秒）
  refresh-expiration: 604800000  # 7天（毫秒）

# 日志配置
logging:
  level:
    com.hunric: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 