server:
  port: 8082

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# 文件上传配置
file:
  upload:
    path: ./uploads  # 文件上传目录
  access:
    base-url: http://localhost:8082  # 文件访问基础URL

# 日志配置
logging:
  level:
    com.hunric: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 